### ISSUE TITLE
Add a releases page

### ISSUE THREAD

**Issue by Taha-Firoz** [SaadBazaz/antiPixel#1]
The current executables folder isn't the most helpful way to give users access to the binaries, I'd suggest we add a [github release](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository). 

I would actually suggest we rewrite this in rust and push out a wasm port and deploy it on a cloudflare worker(if thats possible).

**Comment by SaadBazaz** [comment]
Thanks for the heads up, @Taha-Firoz . When I first uploaded this, I didn't really know much about Github.

I've been wanting to rewrite this for a while now. I've been looking for the **most efficient MASM animation code ever**. I haven't found it yet. When I do, I'd definitely consider deploying it online.

Until then, I'm with you. I'd love to write it in Rust. This code can be built upon to make a sweet and stylish photo editor + animator for indie console games.

**Comment by Taha-Firoz** [comment]
There would be no point in actually rewriting it in rust unless we're planning to target wasm, maybe make just a release page until then.

**Comment by SaadBazaz** [comment]
That's done! Basic Release page created.
Whenever you're ready, you can send a Pull Request in Rust, and we can start building a "Rust" branch.
